spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://postgres:5432/url_shortener_db
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false


  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: url-shortener-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages:
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

# FIXED: Redisson configuration - changed localhost to redis
redisson:
  singleServerConfig:
    address: "redis://redis:6379"
    connectionMinimumIdleSize: 10
    connectionPoolSize: 64

logging:
  level:
    root: INFO
    com.wastech.url_shortener: DEBUG # Your application's base package
    org.hibernate.SQL: DEBUG         # To see SQL statements
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE